//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Accounts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Accounts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestProject1.TestData.Accounts", typeof(Accounts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test17@4teamcorp.com.
        /// </summary>
        internal static string exchangeServiceLogin {
            get {
                return ResourceManager.GetString("exchangeServiceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing107.
        /// </summary>
        internal static string exchangeServicePass {
            get {
                return ResourceManager.GetString("exchangeServicePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4teamgts2@gmail.com.
        /// </summary>
        internal static string googleLogin {
            get {
                return ResourceManager.GetString("googleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labaslabas.
        /// </summary>
        internal static string googlePass {
            get {
                return ResourceManager.GetString("googlePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4teamtests5@gmail.com.
        /// </summary>
        internal static string googleServiceLogin {
            get {
                return ResourceManager.GetString("googleServiceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing107.
        /// </summary>
        internal static string googleServicePass {
            get {
                return ResourceManager.GetString("googleServicePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4teamtests5@gmail.com.
        /// </summary>
        internal static string googleSignUpAccount {
            get {
                return ResourceManager.GetString("googleSignUpAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing107.
        /// </summary>
        internal static string googleSignUpPassword {
            get {
                return ResourceManager.GetString("googleSignUpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t4team10@icloud.com.
        /// </summary>
        internal static string iCloudServiceLogin {
            get {
                return ResourceManager.GetString("iCloudServiceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilnius2014.
        /// </summary>
        internal static string iCloudServicePass {
            get {
                return ResourceManager.GetString("iCloudServicePass", resourceCulture);
            }
        }
    }
}
